### ISSUE TITLE
倾斜摄影web展示有什么方案吗，求交流指导

### ISSUE THREAD

**Issue by sparksofire** [alex2wong/ThreejsDemo#1]

**Comment by alex2wong** [comment]
目前大部分应该都是基于ThreeJS 的展示方案，就是解析 倾斜摄影生成的 分层级mesh，一块一块渲染，再贴图。 具体实现不是很懂，但是现成的有很多， Acute3D，Pix4， 或者 ArcGIS 的drone2map都可以自动生成 web APP

**Comment by sparksofire** [comment]
谢谢
